behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 100000
      learning_rate: 0.0003
    network_settings:
      num_layers: 2
      hidden_units: 128
      vis_encode_type: simple
      memory:
        memory_size: 256
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
